import field from '@/assets/agriculture-hero.jpg';
import seedling from '@/assets/seedling.jpg';
import research from '@/assets/research.jpg';

export { field, seedling, research };
export const articles = [
  { slug: 'smarter-delivery-healthier-soil', title: 'Smarter delivery. Healthier soil. A better way to grow.', category: 'Sustainable agriculture', image: seedling, read: '5 min read', intro: 'Why the future of agriculture starts with how we deliver nutrients, not simply how much we apply.', paragraphs: ['Healthy soil is a living system. Roots, water, nutrients, and microorganisms work together to support each new season of growth. Yet conventional input delivery can allow nutrients to move away from the plants that need them.', 'Controlled delivery takes a different approach: placing active molecules where they are needed and regulating their availability over time. The goal is to improve how effectively plants use agricultural inputs while limiting environmental losses.', 'At Ecovion, sustainable agriculture is our first application vertical. Our material platform is being developed to support root-zone delivery of fertilizers and pesticides, with pilot-scale validation progressing toward field trials.', 'Better delivery is not a substitute for good agronomy. It is one part of a more thoughtful approach to soil stewardship, practical farm management, and long-term resilience.'] },
  { slug: 'science-beneath-the-surface', title: 'The science beneath the surface', category: 'Material science', image: research, read: '4 min read', intro: 'Exploring how smart material systems can regulate the behavior of active molecules.', paragraphs: ['A material is more than a container. Its structure and interactions with its surroundings can influence when and where an active molecule becomes available.', 'Ecovion is developing proprietary material systems for controlled delivery and environmental remediation. Soil, water, and biological interfaces each present different challenges, which is why context matters as much as chemistry.', 'Our platform-led approach starts with understanding the application, designing the material system, and validating its behavior under increasingly realistic conditions.', 'Moving from the laboratory to the field requires careful testing. Ecovion is currently progressing from pilot-scale validation toward field trials and commercialization.'] },
  { slug: 'root-zone-delivery', title: 'Right at the roots: rethinking agricultural inputs', category: 'Sustainable agriculture', image: field, read: '6 min read', intro: 'A closer look at root-zone placement and the opportunities it creates for more efficient farming.', paragraphs: ['The root zone is where plants draw much of the water and nutrition they need. Delivering agricultural inputs closer to this interface can change how they interact with both the crop and its environment.', 'Surface application and spraying can expose inputs to environmental pathways such as drift, sunlight degradation, or leaching. Root-zone delivery is being explored as an alternative way to address these challenges.', 'Ecovion’s agriculture work focuses on smart fertilizer delivery and cleaner pesticide delivery. Both applications build on a common material-innovation platform.', 'Every crop and field is different. Field validation, local conditions, and farmer feedback remain essential before drawing conclusions about practical performance.'] },
] as const;
export const products = [
  { id: 'nutrients', name: 'Smart nutrient delivery', category: 'Agriculture', stage: 'In development', image: seedling, description: 'Material systems designed for controlled nutrient availability in the root zone.', detail: 'Our first agricultural application explores controlled fertilizer delivery to improve nitrogen-use efficiency and reduce nutrient losses. Pilot-scale validation is progressing toward field trials. Final specifications and availability have not been announced.' },
  { id: 'protection', name: 'Root-zone crop protection', category: 'Agriculture', stage: 'In development', image: field, description: 'A more targeted approach to delivering crop-protection molecules.', detail: 'Root-zone placement systems are being developed to address spray drift, ultraviolet degradation, and repeated application. These are development-stage solutions, not products currently available for purchase.' },
  { id: 'water', name: 'Water remediation materials', category: 'Environment', stage: 'Future application', image: research, description: 'Exploring materials for phosphate and nitrate capture in water.', detail: 'Environmental remediation is a future application area for the Ecovion platform, including exploration of phosphate and nitrate capture. Product names, specifications, and launch dates are not yet announced.' },
  { id: 'biological', name: 'Biological-interface delivery', category: 'Healthcare', stage: 'Future application', image: research, description: 'Future opportunities at the intersection of materials and biological systems.', detail: 'Healthcare is a future application vertical for the materials platform. This is an exploratory area, not an approved medical product or a treatment claim. Specific applications and timelines have not been announced.' },
];
export function pageHead(title: string, description: string) {
  return { meta: [{ title: `${title} — Ecovion` }, { name: 'description', content: description }, { property: 'og:title', content: `${title} — Ecovion` }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] };
}