import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowDown, Sprout, Droplets, FlaskConical, Leaf, MoveRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PartnerBand } from '@/components/site-shell';
import { field, seedling, research, pageHead } from '@/lib/site-data';
import { getBlogs } from '@/lib/firebase-db';

const handleShare = (e: React.MouseEvent, title: string, slug: string) => {
  e.preventDefault();
  const url = `${window.location.origin}/blog/${slug}`;
  if (navigator.share) {
    navigator.share({ title, url }).catch(console.error);
  } else {
    navigator.clipboard.writeText(url);
    alert('Article link copied to clipboard!');
  }
};

export const Route = createFileRoute('/')({ 
  loader: async () => await getBlogs(),
  head: () => pageHead('Smart materials. Lasting impact.', 'Ecovion is building smart material systems for more sustainable agriculture, controlled delivery, and a healthier planet.'), 
  component: Index 
});

function Index() {
  const articles = Route.useLoaderData();
  return <>
    <section className="home-hero"><img className="hero-image" src={field} alt="Lush crop rows stretching toward the hills at sunrise" width={1920} height={1024} /><div className="hero-shade" /><div className="site-container hero-content"><span className="hero-eyebrow"><span />SCIENCE-LED. EARTH-FOCUSED.</span><h1>Smart materials<span className="golden-solid">.</span><br />Lasting <span className="golden-outline">impact</span><span className="golden-solid">.</span></h1><p>A smarter way to nourish crops.<br />A gentler way to protect our planet.</p><div className="hero-actions"><Button asChild className="hero-primary"><Link to="/technology">Explore our technology <ArrowUpRight /></Link></Button><Button asChild variant="ghost" className="hero-secondary"><Link to="/about">The Ecovion story <ArrowUpRight /></Link></Button></div><div className="hero-bottom"><span><span className="live-dot" /> ROOTED IN SCIENCE. GROWING WITH PURPOSE.</span><a href="#our-purpose" aria-label="Discover our purpose"><ArrowDown size={20}/></a></div></div><div className="hero-caption"><Leaf size={15}/> Better for crops. Better for the earth.</div></section>
    <div className="trust-band"><div className="site-container"><span>IDEAS NURTURED BY</span><div className="incubator"><span className="incubator-seal"><img src="/pusa-krishi-logo.png" alt="Pusa Krishi Logo" /></span><div><strong>ICAR–IARI</strong><small>Pusa Krishi · Incubation ecosystem</small></div></div><span className="trust-divider"/><p>From material science to meaningful change.</p><span className="india-tag"><span/> MADE IN INDIA. FOR A BETTER WORLD.</span></div></div>
    <section id="our-purpose" className="purpose-section site-container"><div className="purpose-heading"><span className="eyebrow"><span className="tiny-dot"/> THE ECOVION DIFFERENCE</span><h2>Small-scale science.<br /><span>Real-world possibilities.</span></h2></div><div className="purpose-copy"><p>We believe a better future starts with better materials.</p><p className="muted-copy">Ecovion is a deep-tech material innovation platform. We design smart systems that deliver the right molecules, in the right place, at the right time — starting with sustainable agriculture.</p><Link to="/about" className="text-link">Meet Ecovion <ArrowUpRight size={18}/></Link></div></section>
    <section className="possibilities-section site-container"><div className="section-line"><span className="eyebrow">ONE PLATFORM. MANY POSSIBILITIES.</span><Link to="/technology" className="text-link">Discover the science <ArrowUpRight size={17}/></Link></div><div className="benefit-grid">{[{icon: Sprout, n:'01', title:'Smarter agriculture', copy:'Controlled root-zone delivery that helps nutrients reach where they matter most.'}, {icon: Droplets,n:'02',title:'A lighter footprint',copy:'Materials designed to reduce input losses and their impact on soil and water.'}, {icon: FlaskConical,n:'03',title:'Innovation that scales',copy:'A versatile materials platform, with possibilities far beyond a single application.'}].map(b => <div key={b.n} className="benefit"><div className="benefit-top"><b.icon size={28} strokeWidth={1.5}/><span>{b.n}</span></div><h3>{b.title}</h3><p>{b.copy}</p></div>)}</div></section>
    <section className="agriculture-section"><div className="site-container agriculture-grid"><div className="agriculture-image"><img src={seedling} alt="A young seedling in healthy soil held gently in two hands" width={1024} height={1024} loading="lazy"/><span><Leaf size={17}/> Our first chapter: agriculture</span></div><div className="agriculture-copy"><span className="eyebrow">FROM THE LAB. TO THE LAND.</span><h2>Healthier soil.<br />Stronger possibilities.</h2><p>The challenge isn’t just what we apply.<br />It’s how we deliver it.</p><p className="muted-copy">Our first application focuses on smart fertilizer and cleaner pesticide delivery — helping agricultural inputs work closer to the roots, with less lost along the way.</p><div className="application-row"><Sprout/><div><h3>Smart fertilizer delivery</h3><p>Controlled nutrient availability. Reduced losses.</p></div><ArrowUpRight size={18}/></div><div className="application-row"><Leaf/><div><h3>Cleaner crop protection</h3><p>Targeted root-zone placement. Less environmental loss.</p></div><ArrowUpRight size={18}/></div><Button asChild><Link to="/technology">See how it works <ArrowUpRight/></Link></Button></div></div></section>
    <section className="future-section site-container"><div className="section-heading"><div><span className="eyebrow">WHAT’S NEXT</span><h2>The future is taking root.</h2></div><Link to="/future-products" className="text-link">Explore future products <ArrowUpRight size={18}/></Link></div><Link to="/future-products" className="future-preview"><img src={research} alt="Agricultural material research in a bright laboratory" loading="lazy" width={1200} height={800}/><div><span className="status-label"><span/> IN DEVELOPMENT</span><h3>A platform built<br />for what comes next.</h3><p>From precision agriculture to environmental remediation. Discover the next possibilities we’re exploring.</p><span className="text-link">Step into the pipeline <ArrowUpRight size={18}/></span></div><span className="future-arrow"><ArrowUpRight size={24}/></span></Link></section>
    <section className="journal-section site-container"><div className="section-heading"><div><span className="eyebrow">THE ECOVION JOURNAL</span><h2>Ideas for a greener tomorrow.</h2></div><Link to="/blog" className="text-link">Visit the journal <ArrowUpRight size={18}/></Link></div><div className="article-grid">{articles.slice(0, 3).map((a: any) => <Link to="/blog/$slug" params={{slug:a.slug}} key={a.slug} className="article-card relative"><div className="article-image relative"><img src={a.image} alt={a.title} width={600} height={400} loading="lazy"/><button onClick={(e) => handleShare(e, a.title, a.slug)} className="absolute top-3 right-3 bg-background/80 hover:bg-background text-foreground p-2 rounded-full backdrop-blur-sm shadow-sm transition-all z-10 hover:scale-105" aria-label="Share article"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg></button></div><div className="article-meta"><span>{a.category}</span><span>By {a.authors ? a.authors.map((x:any)=>x.name).join(', ') : a.author}</span></div><h3>{a.title}</h3><span className="read-story">Read story <MoveRight size={17}/></span></Link>)}</div></section>
    <PartnerBand />
  </>;
}
