import { Link, useRouterState } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, AlignRight, X, Leaf, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';


const navigation = [{ to: '/', label: 'Home' }, { to: '/about', label: 'About us' }, { to: '/technology', label: 'Our technology' }, { to: '/future-products', label: 'Future products' }, { to: '/blog', label: 'Blog' }] as const;
export function Brand() { return <Link to="/" className="brand" aria-label="Ecovion home"><img src="/Ecovion%20horizontal%20Logo.png" alt="Ecovion" /></Link>; }
export function Header() {
  const [open, setOpen] = useState(false);
  const pathname = useRouterState({ select: s => s.location.pathname });
  return <header className="site-header"><div className="site-container header-inner"><Brand /><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(n => <Link key={n.to} to={n.to} className={pathname === n.to ? 'nav-link active' : 'nav-link'}>{n.label}{n.to === '/future-products' && <span className="nav-new">NEW</span>}</Link>)}</nav><Button asChild className="contact-button desktop-contact-button"><Link to="/contact">Let’s connect <ArrowUpRight /></Link></Button><Button variant="ghost" size="icon" className="mobile-menu-button" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <AlignRight />}</Button></div>{open && <nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(n => <Link key={n.to} to={n.to} onClick={() => setOpen(false)}>{n.label}</Link>)}<Button asChild className="contact-button w-max mt-2"><Link to="/contact" onClick={() => setOpen(false)}>Let’s connect <ArrowUpRight size={16} /></Link></Button></nav>}</header>;
}
export function Footer() { return <footer className="site-footer"><div className="site-container footer-main"><div><Brand /><p>Better materials.<br />A better tomorrow.</p><span className="footer-india">Rooted in India. Built for the world.</span></div><div><h3>Explore</h3><Link to="/about">About Ecovion</Link><Link to="/technology">Our technology</Link><Link to="/future-products">Future products</Link></div><div><h3>Discover</h3><Link to="/blog">The Ecovion journal</Link><Link to="/for-farmers">For farmers</Link><Link to="/contact">Partner with us</Link></div><div><h3>Get in touch</h3><a href="mailto:info.ecovion@gmail.com">info.ecovion@gmail.com <ArrowUpRight size={14}/></a><a href="tel:+917903062113">+91 79030 62113</a><p className="footer-address">Saharanpur, Uttar Pradesh<br />India</p></div></div><div className="site-container footer-bottom"><span>© 2026 Ecovion. All rights reserved.</span><span><Leaf size={14} /> Innovation with the planet in mind.</span><a href="https://www.linkedin.com/company/ecovion-pvt-ltd/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a></div></footer>; }
export function PartnerBand() { return <section className="partner-band"><div className="site-container"><div><span className="eyebrow">LET’S GROW SOMETHING BETTER</span><h2>Big ideas grow<br />through collaboration.</h2></div><div><p>Researchers, farmers, and forward-thinkers.<br />There’s a place for you in our journey.</p><Button asChild className="light-button"><Link to="/contact">Partner with Ecovion <ArrowUpRight /></Link></Button></div></div></section>; }
export function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <section className="page-intro site-container"><span className="eyebrow"><span className="tiny-dot" />{eyebrow}</span><h1>{title}</h1><p>{description}</p></section>; }