/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Admincontrol108RouteImport } from './routes/admincontrol108'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForFarmersRouteImport } from './routes/for-farmers'
import { Route as FutureProductsRouteImport } from './routes/future-products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Admincontrol108Route = Admincontrol108RouteImport.update({
  id: '/admincontrol108',
  path: '/admincontrol108',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFarmersRoute = ForFarmersRouteImport.update({
  id: '/for-farmers',
  path: '/for-farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureProductsRoute = FutureProductsRouteImport.update({
  id: '/future-products',
  path: '/future-products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admincontrol108': typeof Admincontrol108Route
  '/contact': typeof ContactRoute
  '/for-farmers': typeof ForFarmersRoute
  '/future-products': typeof FutureProductsRoute
  '/privacy': typeof PrivacyRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admincontrol108': typeof Admincontrol108Route
  '/contact': typeof ContactRoute
  '/for-farmers': typeof ForFarmersRoute
  '/future-products': typeof FutureProductsRoute
  '/privacy': typeof PrivacyRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admincontrol108': typeof Admincontrol108Route
  '/contact': typeof ContactRoute
  '/for-farmers': typeof ForFarmersRoute
  '/future-products': typeof FutureProductsRoute
  '/privacy': typeof PrivacyRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admincontrol108'
    | '/contact'
    | '/for-farmers'
    | '/future-products'
    | '/privacy'
    | '/technology'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admincontrol108'
    | '/contact'
    | '/for-farmers'
    | '/future-products'
    | '/privacy'
    | '/technology'
    | '/terms'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admincontrol108'
    | '/contact'
    | '/for-farmers'
    | '/future-products'
    | '/privacy'
    | '/technology'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Admincontrol108Route: typeof Admincontrol108Route
  ContactRoute: typeof ContactRoute
  ForFarmersRoute: typeof ForFarmersRoute
  FutureProductsRoute: typeof FutureProductsRoute
  PrivacyRoute: typeof PrivacyRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admincontrol108': {
      id: '/admincontrol108'
      path: '/admincontrol108'
      fullPath: '/admincontrol108'
      preLoaderRoute: typeof Admincontrol108RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-farmers': {
      id: '/for-farmers'
      path: '/for-farmers'
      fullPath: '/for-farmers'
      preLoaderRoute: typeof ForFarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-products': {
      id: '/future-products'
      path: '/future-products'
      fullPath: '/future-products'
      preLoaderRoute: typeof FutureProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Admincontrol108Route: Admincontrol108Route,
  ContactRoute: ContactRoute,
  ForFarmersRoute: ForFarmersRoute,
  FutureProductsRoute: FutureProductsRoute,
  PrivacyRoute: PrivacyRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
